### PR TITLE
Yah, there's no Swift in that directory.

### PR DESCRIPTION
**Pull request by neonichu**
Also the C headers are required, kinda gross, yo.

### CODE REVIEW

**Comment by a2** [comment]
But Gulliver.h shouldn't be included because CP makes that?

**Comment by neonichu** [comment]
Since `FOUNDATION_EXPORT` is just a fancy way of saying `extern`, it doesn't actually matter.

**Comment by a2** [comment]
What about Info.plist?

**Comment by neonichu** [comment]
That'll be ignored, CP is smart enough to only pick out files with relevant extensions: https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/sandbox/file_accessor.rb#L15

**Comment by a2** [comment]
Alright. :)

**Pull request merged**
